- name: Installation de Docker et Setup API
  hosts: api
  become: yes
  vars:
    docker_packages:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-pip

  tasks:
    # --- INSTALLATION DOCKER ---
    - name: 1. Mise à jour du cache APT
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: 2. Installation des pré-requis
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ docker_packages }}"

    - name: 3. Clé GPG Docker
      shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg --yes
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: 4. Dépôt Docker
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: 5. Install Docker Engine
      apt:
        update_cache: yes
        name: [docker-ce, docker-ce-cli, containerd.io, docker-buildx-plugin, docker-compose-plugin]
        state: present

    - name: 6. User ubuntu dans groupe docker
      user:
        name: ubuntu
        groups: docker
        append: yes

    # --- FIX PYTHON ---
    - name: 7. Installation Librairie Docker pour Python (FIX COMPATIBILITÉ)
      pip:
        name:
          - docker==6.1.3
          - urllib3==1.26.15
          - requests==2.28.2
        executable: pip3
        state: forcereinstall

    # --- DÉPLOIEMENT API ---
    - name: 8. Créer le dossier pour l'API
      file:
        path: /home/ubuntu/api
        state: directory
        mode: '0755'

    - name: 9. Copier le code et le modèle vers le serveur
      copy:
        src: ../api/
        dest: /home/ubuntu/api/
        mode: '0644'
        directory_mode: '0755'

    - name: 10. Construire l'image Docker API
      docker_image:
        name: mlops-api
        source: build
        build:
          path: /home/ubuntu/api
        force_source: yes

    - name: 11. Lancer le conteneur API
      docker_container:
        name: api_server
        image: mlops-api
        state: started
        restart_policy: always
        ports:
          - "5000:5000"